const express = require('express');
const app = express();
const errorHandler = require("./middlewares/errorMiddleware");
const connectDB = require('./config/connect');
require("dotenv").config();
require("colors");
const port = process.env.PORT;
const cors = require('cors');
app.use(cors());
connectDB();
app.use(express.json());
app.use(express.urlencoded({extended:false}));
app.use('/api/sham', require('./routes/shamRoutes'));
app.use("/api/user", require("./routes/userRoutes"));
app.use(errorHandler);
app.listen(port,()=> console.log(`Server Started On Port:${port.cyan}`));